<?php

declare(strict_types=1);

namespace Ethelserth\Biblionet\DTOs;

final class Title
{
    public function __construct(
        public readonly int $titlesId,
        public readonly string $title,
        public readonly ?string $subtitle,
        public readonly ?string $parallelTitle,
        public readonly ?string $alternativeTitle,
        public readonly ?string $originalTitle,
        public readonly ?string $isbn,
        public readonly ?string $isbn2,
        public readonly ?string $isbn3,
        public readonly ?string $ismn,
        public readonly int $publisherId,
        public readonly string $publisher,
        public readonly int $writerId,
        public readonly string $writer,
        public readonly string $writerName,
        public readonly ?string $firstPublishDate,
        public readonly ?string $currentPublishDate,
        public readonly ?string $futurePublishDate,
        public readonly ?string $place,
        public readonly string $titleType,
        public readonly ?int $editionNo,
        public readonly ?string $cover,
        public readonly ?string $dimensions,
        public readonly ?int $pageNo,
        public readonly string $availability,
        public readonly ?string $price,
        public readonly ?int $vat,
        public readonly ?int $weight,
        public readonly ?int $ageFrom,
        public readonly ?int $ageTo,
        public readonly ?string $summary,
        public readonly ?string $language,
        public readonly ?string $languageOriginal,
        public readonly ?string $languageTranslatedFrom,
        public readonly ?string $contains,
        public readonly ?string $series,
        public readonly ?string $seriesNo,
        public readonly ?string $subSeries,
        public readonly ?string $subSeriesNo,
        public readonly ?string $multiVolumeTitle,
        public readonly ?string $setIsbn,
        public readonly ?string $volumeNo,
        public readonly ?int $volumeCount,
        public readonly ?string $specifications,
        public readonly ?string $webAddress,
        public readonly ?string $comments,
        public readonly int $categoryId,
        public readonly string $category,
        public readonly ?string $coverImage,
        public readonly ?string $lastUpdate,
    ) {}

    public static function fromApiResponse(array $data): self
    {
        return new self(
            titlesId: (int) $data['TitlesID'],
            title: $data['Title'],
            subtitle: $data['Subtitle'] !== '' ? $data['Subtitle'] : null,
            parallelTitle: $data['ParallelTitle'] !== '' ? $data['ParallelTitle'] : null,
            alternativeTitle: $data['AlternativeTitle'] !== '' ? $data['AlternativeTitle'] : null,
            originalTitle: $data['OriginalTitle'] !== '' ? $data['OriginalTitle'] : null,
            isbn: $data['ISBN'] !== '' ? $data['ISBN'] : null,
            isbn2: $data['ISBN_2'] !== '' ? $data['ISBN_2'] : null,
            isbn3: $data['ISBN_3'] !== '' ? $data['ISBN_3'] : null,
            ismn: $data['ISMN'] !== '' ? $data['ISMN'] : null,
            publisherId: (int) $data['PublisherID'],
            publisher: $data['Publisher'],
            writerId: (int) $data['WriterID'],
            writer: $data['Writer'],
            writerName: $data['WriterName'],
            firstPublishDate: $data['FirstPublishDate'] ?? null,
            currentPublishDate: $data['CurrentPublishDate'] ?? null,
            futurePublishDate: $data['FuturePublishDate'] ?? null,
            place: isset($data['Place']) && $data['Place'] !== '' ? $data['Place'] : null,
            titleType: $data['TitleType'],
            editionNo: isset($data['EditionNo']) ? (int) $data['EditionNo'] : null,
            cover: isset($data['Cover']) && $data['Cover'] !== '' ? $data['Cover'] : null,
            dimensions: isset($data['Dimensions']) && $data['Dimensions'] !== '' ? $data['Dimensions'] : null,
            pageNo: isset($data['PageNo']) && $data['PageNo'] !== '' ? (int) $data['PageNo'] : null,
            availability: $data['Availability'],
            price: isset($data['Price']) && $data['Price'] !== '' ? $data['Price'] : null,
            vat: isset($data['VAT']) && $data['VAT'] !== '' ? (int) $data['VAT'] : null,
            weight: isset($data['Weight']) && $data['Weight'] !== '' ? (int) $data['Weight'] : null,
            ageFrom: isset($data['AgeFrom']) ? (int) $data['AgeFrom'] : null,
            ageTo: isset($data['AgeTo']) ? (int) $data['AgeTo'] : null,
            summary: isset($data['Summary']) && $data['Summary'] !== '' ? $data['Summary'] : null,
            language: isset($data['Language']) && $data['Language'] !== '' ? $data['Language'] : null,
            languageOriginal: isset($data['LanguageOriginal']) && $data['LanguageOriginal'] !== '' ? $data['LanguageOriginal'] : null,
            languageTranslatedFrom: isset($data['LanguageTranslatedFrom']) && $data['LanguageTranslatedFrom'] !== '' ? $data['LanguageTranslatedFrom'] : null,
            contains: $data['Contains'] ?? null,
            series: isset($data['Series']) && $data['Series'] !== '' ? $data['Series'] : null,
            seriesNo: $data['SeriesNo'] ?? null,
            subSeries: $data['SubSeries'] ?? null,
            subSeriesNo: $data['SubSeriesNo'] ?? null,
            multiVolumeTitle: $data['MultiVolumeTitle'] ?? null,
            setIsbn: $data['SetISBN'] ?? null,
            volumeNo: $data['VolumeNo'] ?? null,
            volumeCount: isset($data['VolumeCount']) ? (int) $data['VolumeCount'] : null,
            specifications: isset($data['Specifications']) && $data['Specifications'] !== '' ? $data['Specifications'] : null,
            webAddress: $data['WebAddress'] ?? null,
            comments: $data['Comments'] ?? null,
            categoryId: (int) $data['CategoryID'],
            category: $data['Category'],
            coverImage: isset($data['CoverImage']) && $data['CoverImage'] !== ''
                ? 'https://biblionet.gr' . $data['CoverImage']
                : null,
            lastUpdate: isset($data['LastUpdate']) && $data['LastUpdate'] !== '' ? $data['LastUpdate'] : null,
        );
    }
}